server:
  port: 8999
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      routes:
      - id: product-service   
        uri: lb://product-service
        predicates:
        - Path=/product/**
        filters:
        - name: CircuitBreaker
          args:
             name: product-service
             fallbackuri: forward:/productServiceFallback
             
#order service

      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/order/**
        filters:
        - name: CircuitBreaker
          args:
             name: order-service
             fallbackuri: forward:/orderServiceFallback 

#airport service             
             
      - id: airport-service
        uri: lb://airport-service
        predicates:
        - Path=/airport/**
        filters:
        - name: CircuitBreaker
          args:
             name: airport-service
             fallbackuri: forward:/airportServiceFallback  
 
 #schedule service             
      - id: schedule-service
        uri: lb://schedule-service
        predicates:
        - Path=/schedule/**
        filters:
        - name: CircuitBreaker
          args:
             name: schedule-service
             fallbackuri: forward:/scheduleServiceFallback  

 #seat service             
      - id: seat-service
        uri: lb://seat-service
        predicates:
        - Path=/seat/**
        filters:
        - name: CircuitBreaker
          args:
             name: seat-service
             fallbackuri: forward:/seatServiceFallback

 #Movie service             
      - id: movie-service
        uri: lb://movie-service
        predicates:
        - Path=/movie/**
        filters:
        - name: CircuitBreaker
          args:
             name: movie-service
             fallbackuri: forward:/movieServiceFallback 
             
#Show service             
      - id: show-service
        uri: lb://show-service
        predicates:
        - Path=/show/**
        filters:
        - name: CircuitBreaker
          args:
             name: show-service
             fallbackuri: forward:/showServiceFallback  
#Screen service             
      - id: screen-service
        uri: lb://screen-service
        predicates:
        - Path=/screen/**
        filters:
        - name: CircuitBreaker
          args:
             name: screen-service
             fallbackuri: forward:/screenServiceFallback 
#Theater service             
      - id: theater-service
        uri: lb://theater-service
        predicates:
        - Path=/theater/**
        filters:
        - name: CircuitBreaker
          args:
             name: theater-service
             fallbackuri: forward:/theaterServiceFallback                                              

#booking-service             
      - id: booking-service
        uri: lb://booking-service
        predicates:
        - Path=/booking/**
        filters:
        - name: CircuitBreaker
          args:
             name: booking-service
             fallbackuri: forward:/bookingServiceFallback 


#ticket-service             
      - id: ticket-service
        uri: lb://ticket-service
        predicates:
        - Path=/ticket/**
        filters:
        - name: CircuitBreaker
          args:
             name: ticket-service
             fallbackuri: forward:/ticketServiceFallback

#customer-service             
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/customer/**
        filters:
        - name: CircuitBreaker
          args:
             name: customer-service
             fallbackuri: forward:/customerServiceFallback
  application:
    name: api-gateway  
            
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
            
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health           